spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/springboot?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
#    ¥Ú”°sql
    show-sql: true

